import {createHmac} from 'node:crypto';
import {contactConfigured,validateContact} from '@/lib/contact';
export const runtime='nodejs';
const unavailable='L’envoi n’est pas encore configuré. Aucun message ne peut être transmis pour le moment.';
export async function POST(request:Request){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return Response.json({message:'Requête non autorisée.'},{status:403});if(Number(request.headers.get('content-length')||0)>20000)return Response.json({message:'Demande trop volumineuse.'},{status:413});let raw;try{const body=await request.text();if(body.length>20000)return Response.json({message:'Demande trop volumineuse.'},{status:413});raw=JSON.parse(body)}catch{return Response.json({message:'Demande invalide.'},{status:400})}const {values,errors}=validateContact(raw);if(Object.keys(errors).length)return Response.json({errors,message:'Veuillez vérifier les champs indiqués.'},{status:400});if(values.website)return Response.json({message:'Demande non transmise.'},{status:400});if(!contactConfigured())return Response.json({message:unavailable},{status:503});try{
// Only use a forwarded IP header when the hosting proxy overwrites it.
const header=process.env.TRUSTED_IP_HEADER;const ip=header?request.headers.get(header)?.split(',')[0].trim():undefined;
const bucket=ip||'shared';const hash=createHmac('sha256',process.env.RATE_LIMIT_SALT!).update(bucket).digest('hex');
const rate=await fetch(process.env.UPSTASH_REDIS_REST_URL!,{method:'POST',headers:{Authorization:`Bearer ${process.env.UPSTASH_REDIS_REST_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify(['EVAL',"local n=redis.call('INCR',KEYS[1]); if n==1 then redis.call('EXPIRE',KEYS[1],600) end; return n",'1',`contact:${hash}`]),signal:AbortSignal.timeout(10000),cache:'no-store'});
const count=await rate.json();if(!rate.ok||typeof count.result!=='number')throw new Error('Rate limit unavailable');if(count.result>5)return Response.json({message:'Trop de demandes. Veuillez réessayer dans dix minutes.'},{status:429});
const text=`Nom : ${values.name}\nEntreprise : ${values.company}\nTéléphone : ${values.phone}\nExpertise : ${values.expertise}\n\n${values.message}`;
const sent=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.CONTACT_FROM,to:[process.env.CONTACT_TO],reply_to:values.email,subject:'Nouvelle demande — Ermita Advisory',text}),signal:AbortSignal.timeout(15000)});const result=await sent.json();if(!sent.ok||typeof result.id!=='string'||!result.id)throw new Error('Delivery rejected');return Response.json({message:'Votre message a bien été envoyé. Merci d’avoir contacté Ermita Advisory.'});
}catch{return Response.json({message:'Votre message n’a pas pu être envoyé. Veuillez réessayer dans quelques instants.'},{status:502})}}
