'use client';
import {useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {expertises} from '@/content/site';
import {validateContact} from '@/lib/contact';
export function ContactForm({configured}:{configured:boolean}){const [busy,setBusy]=useState(false);const locked=useRef(false);const [errors,setErrors]=useState<Record<string,string>>({});const [status,setStatus]=useState('');const form=useRef<HTMLFormElement>(null);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(locked.current)return;const data=Object.fromEntries(new FormData(event.currentTarget));const checked=validateContact(data);setErrors(checked.errors);if(Object.keys(checked.errors).length){form.current?.querySelector<HTMLElement>(`[name="${Object.keys(checked.errors)[0]}"]`)?.focus();return}locked.current=true;setBusy(true);setStatus('');try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(checked.values)});const result=await res.json();setErrors(result.errors||{});setStatus(result.message);if(res.ok)form.current?.reset()}catch{setStatus('Votre message n’a pas pu être envoyé. Veuillez réessayer dans quelques instants.')}finally{locked.current=false;setBusy(false)}}
function field(name:string,label:string,type='text',required=false){return <div className="form-field"><label htmlFor={name}>{label}{required?' *':' (facultatif)'}</label><input id={name} name={name} type={type} required={required} maxLength={name==='email'?254:150} minLength={name==='name'?2:undefined} autoComplete={{name:'name',email:'email',company:'organization',phone:'tel'}[name]} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<span id={`${name}-error`} className="field-error">{errors[name]}</span>}</div>}
return <form ref={form} onSubmit={submit} noValidate><p className="text-sm">Les champs marqués d’un astérisque sont requis.</p>{!configured&&<p className="form-note" role="status">L’envoi n’est pas encore configuré. Aucun message ne peut être transmis pour le moment.</p>}<div className="form-grid">{field('name','Nom et prénom','text',true)}{field('email','E-mail professionnel','email',true)}{field('company','Entreprise')}{field('phone','Téléphone','tel')}<div className="form-field full"><label htmlFor="expertise">Expertise concernée (facultatif)</label><select name="expertise" id="expertise"><option value="">Sélectionner une expertise</option>{expertises.map(e=><option key={e.slug}>{e.name}</option>)}<option>Autre demande</option></select></div><div className="form-field full"><label htmlFor="message">Message *</label><textarea id="message" name="message" required minLength={10} maxLength={5000} rows={6} placeholder="Décrivez votre situation, votre objectif et, si vous en avez une, votre échéance." aria-invalid={Boolean(errors.message)} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<span id="message-error" className="field-error">{errors.message}</span>}</div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Site web</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div></div><p className="mt-6 text-sm">Les informations saisies servent à traiter votre demande. Consultez notre <Link href="/confidentialite" className="underline">politique de confidentialité</Link>. Le traitement définitif reste à valider avant l’activation de l’envoi.</p><button className="button submit" disabled={!configured||busy} type="submit">{busy?'Envoi en cours…':'Envoyer ma demande'}<span aria-hidden="true">⟶</span></button><p className="form-status" role="status" aria-live="polite">{status}</p></form>}
