const {chromium}=require('@playwright/test');
const fs=require('fs');
const assert=require('node:assert/strict');
const routes=['/','/le-cabinet','/expertises/ingenierie-financiere','/expertises/pilotage-et-performance','/expertises/strategie-et-management','/expertises/accompagnement-de-projets','/contact','/mentions-legales','/confidentialite'];
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});for(const route of routes){const response=await page.goto('http://127.0.0.1:3000'+route);assert.equal(response.status(),200);await page.evaluate(()=>document.fonts.ready);await page.locator('footer').scrollIntoViewIfNeeded();await page.evaluate(async()=>{await Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=r;img.onerror=r})));window.scrollTo(0,0)});assert.equal(await page.locator('h1').count(),1);const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(dimensions.scroll<=width,`${route} overflow ${width}: ${dimensions.scroll}`);const links=await page.locator('a').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')));assert.ok(links.every(h=>h&&h!=='#'));results.push({route,width,status:response.status(),overflow:false});if((route==='/'||route==='/expertises/ingenierie-financiere')&&[390,1440].includes(width))await page.screenshot({path:`verification/${route==='/'?'accueil':'expertise'}-${width}.png`,fullPage:true});}}
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3000');const toggle=page.locator('.menu-toggle');await toggle.focus();await page.keyboard.press('Enter');assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert.ok(await toggle.evaluate(el=>el===document.activeElement));await toggle.click();await page.locator('#mobile-navigation').getByRole('link',{name:'Nos expertises',exact:true}).click();await page.waitForURL('**/#expertises');assert.equal(await toggle.getAttribute('aria-expanded'),'false');await page.goto('http://127.0.0.1:3000/expertises/ingenierie-financiere');assert.equal(await page.locator('#mobile-navigation a[href="/#expertises"]').getAttribute('aria-current'),'page');
await page.goto('http://127.0.0.1:3000/contact');assert.ok(await page.getByRole('button',{name:'Envoyer ma demande'}).isDisabled());
for(const route of ['/inconnue','/expertises/inconnue']){const res=await page.goto('http://127.0.0.1:3000'+route);assert.equal(res.status(),404)}
for(const route of routes){const res=await page.request.get('http://127.0.0.1:3000'+route);const html=await res.text();const hrefs=[...html.matchAll(/href="(\/[^"]*)"/g)].map(m=>m[1]);for(const href of new Set(hrefs.filter(x=>!x.startsWith('/_next')&&!x.includes('#')))){const linked=await page.request.get('http://127.0.0.1:3000'+href);assert.equal(linked.status(),200,`Broken link ${href}`)}}
assert.deepEqual(errors,[]);fs.writeFileSync('verification/browser-results.json',JSON.stringify({results,menu:'passed',links:'passed',notFound:'passed',unconfiguredForm:'passed',pageErrors:errors},null,2));await browser.close();console.log('Browser checks passed: 36 route/viewport combinations, navigation, links, 404 and unconfigured form.');})().catch(e=>{console.error(e);process.exit(1)});


